# Generated by Django 3.0.6 on 2020-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_info',
            field=models.TextField(blank=True, default='No infomation', null=True, verbose_name='ArtistInfo'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Company'),
        ),
    ]
