# Generated by Django 3.0.6 on 2020-05-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0002_auto_20200517_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='debut',
            field=models.DateField(blank=True, null=True, verbose_name='Debut year'),
        ),
    ]
