# Generated by Django 3.0.6 on 2020-05-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0003_auto_20200517_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='sibal', help_text='one word for title alias.', unique=True, verbose_name='Slug'),
        ),
    ]
