# Generated by Django 3.0.6 on 2020-05-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0005_auto_20200517_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='slug',
        ),
    ]
