# Generated by Django 3.0.6 on 2020-05-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0008_auto_20200517_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='sibal', help_text='one word for title alias.', unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='sibal', help_text='one word for title alias.', unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='sibal', help_text='one word for title alias.', unique=True, verbose_name='Slug'),
        ),
    ]
