# Generated by Django 3.0.6 on 2020-05-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0009_auto_20200517_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='one word for title alias.', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='one word for title alias.', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='one word for title alias.', unique=True, verbose_name='Slug'),
        ),
    ]
