# Generated by Django 3.0.6 on 2020-05-18 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0010_auto_20200517_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicb.Album'),
            preserve_default=False,
        ),
    ]
