# Generated by Django 3.0.6 on 2020-05-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0012_auto_20200518_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
