# Generated by Django 3.0.6 on 2020-05-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0013_auto_20200518_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Track',
        ),
    ]
