# Generated by Django 3.0.6 on 2020-05-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0014_auto_20200520_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='debut',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
