# Generated by Django 3.0.6 on 2020-05-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0015_auto_20200520_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_info',
            field=models.TextField(blank=True, default='There is no information.', null=True, verbose_name='ArtistInfo'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='company',
            field=models.CharField(blank=True, default='No company', max_length=50, null=True, verbose_name='Company'),
        ),
    ]
