# Generated by Django 3.0.6 on 2020-05-20 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0016_auto_20200520_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='debut',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
