# Generated by Django 3.0.6 on 2020-05-20 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0017_auto_20200520_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='debut',
            field=models.PositiveIntegerField(blank=True, default=2020, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
