# Generated by Django 3.0.6 on 2020-05-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0018_auto_20200520_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='lyric',
            field=models.TextField(blank=True, default='There is no lyrics yet.', null=True, verbose_name='lyrics'),
        ),
    ]
