# Generated by Django 3.0.6 on 2020-05-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0019_track_lyric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='lyric',
            new_name='lyrics',
        ),
    ]
