# Generated by Django 3.0.6 on 2020-05-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicb', '0020_auto_20200520_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='musicb.Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='musicb.Artist'),
        ),
    ]
